version: "3.9"

services:
  gitfiles:
    image: alpine
    volumes:
      - ./site:/app:ro
    command: sleep infinity
    labels:
      - "traefik.enable=false"

  init:
    image: alpine
    depends_on:
      - gitfiles
    working_dir: /app
    command: sh -c "cp -r /app/* /target/"
    volumes:
      - site-2bpo-volume:/target
      - ./site:/app:ro
    labels:
      - "traefik.enable=false"

  site:
    image: nginx:alpine
    volumes:
      - site-2bpo-volume:/usr/share/nginx/html:ro
    networks:
      - network_public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site-estatico.rule=Host(`mkt.2bpo.com.br`)"
      - "traefik.http.routers.site-estatico.entrypoints=websecure"
      - "traefik.http.routers.site-estatico.tls=true"
      - "traefik.http.routers.site-estatico.tls.certresolver=letsencrypt"
      - "traefik.http.services.site-estatico.loadbalancer.server.port=80"

volumes:
  site-2bpo-volume:

networks:
  network_public:
    external: true
